spring.application.name=EventsManagement

# Persistent H2 database stored in project folder
spring.datasource.url=jdbc:h2:file:./data/univentsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate settings (update schema without dropping existing data)
spring.jpa.hibernate.ddl-auto=update